### PR TITLE
Changed private to protected because we need to inherit the variables.

### PR DESCRIPTION
**Pull request by VijayaGB98**

### CODE REVIEW

**Comment by VijayaGB98** [comment]
Alright

**Comment by VijayaGB98** [comment]
Ok I will make the prices final.

**Comment by Kelvin1337** [comment]
Also , we need to stage only the java files. Each of us can compile them. Staging the .xml and etc is not neccessary and creates confusion, (eg : CinemSystem and CinemaSystem-1 in your case)

**Comment by VijayaGB98** [comment]
Oh lol I haven’t used git kraken at all. I will stick to cmd if you don’t
mind. Ok I will commit specific files.

**Comment by VijayaGB98** [comment]
Also Preetika needs help with creating a branch?

**Pull request closed without merging**
